/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.analysis;

import nl.vu.cs.mvermaat.britney.grammar.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object in);
    Object getOut(Node node);
    void setOut(Node node, Object out);

    void caseStart(Start node);
    void caseAVariableTerm(AVariableTerm node);
    void caseAAbstractionTerm(AAbstractionTerm node);
    void caseAApplicationTerm(AApplicationTerm node);

    void caseTHead(THead node);
    void caseTBody(TBody node);
    void caseTVariable(TVariable node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
}
