/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.lexer;

public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
