/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.node;

import java.util.*;
import nl.vu.cs.mvermaat.britney.grammar.analysis.*;

public final class AAbstractionTerm extends PTerm
{
    private TVariable _variable_;
    private PTerm _term_;

    public AAbstractionTerm()
    {
    }

    public AAbstractionTerm(
        TVariable _variable_,
        PTerm _term_)
    {
        setVariable(_variable_);

        setTerm(_term_);

    }
    public Object clone()
    {
        return new AAbstractionTerm(
            (TVariable) cloneNode(_variable_),
            (PTerm) cloneNode(_term_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAbstractionTerm(this);
    }

    public TVariable getVariable()
    {
        return _variable_;
    }

    public void setVariable(TVariable node)
    {
        if(_variable_ != null)
        {
            _variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _variable_ = node;
    }

    public PTerm getTerm()
    {
        return _term_;
    }

    public void setTerm(PTerm node)
    {
        if(_term_ != null)
        {
            _term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _term_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_variable_)
            + toString(_term_);
    }

    void removeChild(Node child)
    {
        if(_variable_ == child)
        {
            _variable_ = null;
            return;
        }

        if(_term_ == child)
        {
            _term_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_variable_ == oldChild)
        {
            setVariable((TVariable) newChild);
            return;
        }

        if(_term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

    }
}
