/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.node;

import java.util.*;
import nl.vu.cs.mvermaat.britney.grammar.analysis.*;

public final class AVariableTerm extends PTerm
{
    private TVariable _variable_;

    public AVariableTerm()
    {
    }

    public AVariableTerm(
        TVariable _variable_)
    {
        setVariable(_variable_);

    }
    public Object clone()
    {
        return new AVariableTerm(
            (TVariable) cloneNode(_variable_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableTerm(this);
    }

    public TVariable getVariable()
    {
        return _variable_;
    }

    public void setVariable(TVariable node)
    {
        if(_variable_ != null)
        {
            _variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _variable_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_variable_);
    }

    void removeChild(Node child)
    {
        if(_variable_ == child)
        {
            _variable_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_variable_ == oldChild)
        {
            setVariable((TVariable) newChild);
            return;
        }

    }
}
