/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.node;

import nl.vu.cs.mvermaat.britney.grammar.analysis.*;

public final class Start extends Node
{
    private PTerm _pTerm_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PTerm _pTerm_,
        EOF _eof_)
    {
        setPTerm(_pTerm_);
        setEOF(_eof_);
    }

    public Object clone()
    {
        return new Start(
            (PTerm) cloneNode(_pTerm_),
            (EOF) cloneNode(_eof_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseStart(this);
    }

    public PTerm getPTerm()
    {
        return _pTerm_;
    }

    public void setPTerm(PTerm node)
    {
        if(_pTerm_ != null)
        {
            _pTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pTerm_ = node;
    }

    public EOF getEOF()
    {
        return _eof_;
    }

    public void setEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _eof_ = node;
    }

    void removeChild(Node child)
    {
        if(_pTerm_ == child)
        {
            _pTerm_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pTerm_ == oldChild)
        {
            setPTerm((PTerm) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            setEOF((EOF) newChild);
            return;
        }
    }

    public String toString()
    {
        return "" +
            toString(_pTerm_) +
            toString(_eof_);
    }
}
