/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.node;

import nl.vu.cs.mvermaat.britney.grammar.analysis.*;

public final class TBody extends Token
{
    public TBody(String text)
    {
        setText(text);
    }

    public TBody(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TBody(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBody(this);
    }
}
