/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.node;

import nl.vu.cs.mvermaat.britney.grammar.analysis.*;

public final class THead extends Token
{
    public THead(String text)
    {
        setText(text);
    }

    public THead(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new THead(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHead(this);
    }
}
