/* This file was generated by SableCC (http://www.sablecc.org/). */

package nl.vu.cs.mvermaat.britney.grammar.node;

import nl.vu.cs.mvermaat.britney.grammar.analysis.*;

public final class TLPar extends Token
{
    public TLPar()
    {
        super.setText("(");
    }

    public TLPar(int line, int pos)
    {
        super.setText("(");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TLPar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLPar(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TLPar text.");
    }
}
